create table users
(
    id bigint generated by default as identity primary key,
    password varchar(255),
    username varchar(255)
);

create table events
(
    id          bigint generated by default as identity primary key,
    duration    integer,
    is_personal boolean,
    author_id   bigint       not null,
    created_at  timestamp(6) not null,
    start_time  timestamp(6),
    description varchar(255),
    status      varchar(255) not null check (status in ('PENDING', 'ACCEPTED')),
    title       varchar(255),
    constraint events_author_id_fk foreign key (author_id) references users on delete cascade,
    constraint duration_check check (duration > 0)
);

create table event_participants
(
    id       bigint generated by default as identity primary key,
    event_id bigint       not null,
    user_id  bigint       not null,
    status   varchar(255) not null check (status in ('PENDING', 'ACCEPTED', 'DECLINED', 'INABILITY')),
    constraint event_participants_event_id_fk foreign key (event_id) references events on delete cascade,
    constraint event_participants_user_id_fk foreign key (user_id) references users on delete cascade,
    constraint unique_participation unique (event_id, user_id)
);

create table days
(
    id                   bigint generated by default as identity primary key,
    date                 date,
    event_participant_id bigint not null,
    constraint days_event_participants_id_fk foreign key (event_participant_id) references event_participants
        on delete cascade
);
