create table users
(
    id       bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    password varchar(255) not null
);

create table events
(
    id         bigint generated by default as identity primary key,
    author_id  bigint not null,
    title      varchar(200) not null,
    start_time timestamp not null,
    end_time   timestamp not null,
    constraint events_author_id_fk foreign key (author_id) references users on delete cascade,
    constraint check_event_dates check (start_time < end_time)
);

create table event_participants
(
    id       bigint generated by default as identity primary key,
    event_id bigint not null,
    user_id  bigint not null,
    status   varchar(10) not null check (status in ('PENDING', 'ACCEPTED', 'DECLINED')),
    constraint event_participants_event_id_fk foreign key (event_id) references events on delete cascade,
    constraint event_participants_user_id_fk foreign key (user_id) references users on delete cascade,
    constraint unique_participation unique (event_id, user_id)
);