create table users
(
    id       bigint generated by default as identity primary key,
    password varchar(255),
    username varchar(255)
);

create table events
(
    id            bigint generated by default as identity primary key,
    author_id     bigint       not null,
    duration      integer,
    start_time    timestamp(6),
    description   varchar(255),
    possible_days JSONB,
    status        varchar(255) not null check (status in ('PENDING', 'ACCEPTED', 'DECLINED')),
    title         varchar(255),
    constraint events_author_id_fk foreign key (author_id) references users on delete cascade,
    constraint duration_check check (duration > 0)
);

create table event_participants
(
    id       bigint generated by default as identity primary key,
    event_id      bigint       not null,
    user_id       bigint       not null,
    status        varchar(255) not null check (status in ('PENDING', 'ACCEPTED', 'DECLINED')),
    selected_days JSONB,
    constraint event_participants_event_id_fk foreign key (event_id) references events on delete cascade,
    constraint event_participants_user_id_fk foreign key (user_id) references users on delete cascade,
    constraint unique_participation unique (event_id, user_id)
);