jwt:
  secret: ${SECRET}
  lifetime: 300m

app:
  base-url-auth: http://localhost:8189
  work-start: "09:00"
  work-end: "23:00"

vk:
  bot:
    enabled: true
    group-id: 237605745
    access-token: ${VK_BOT_TOKEN}
    reminder-minutes-before: 15
    code-ttl-minutes: 1
    max-attempts: 3

spring:
  application:
    name: meeting-site
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create
    show-sql: false

server:
  port: 8189

springdoc:
  swagger-ui:
    path: /swagger-ui