jwt:
  secret: ${SECRET}
  lifetime: 300m

app:
  base-url-auth: http://localhost:8189

spring:
  application:
    name: meeting-site
  jackson:
    time-zone: UTC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8189

springdoc:
  swagger-ui:
    path: /swagger-ui